version: "3.9"
services:
    app:
        build:
            context: website/
            dockerfile: ./Dockerfile
            args:
                NEXT_PUBLIC_CLIENTVAR: "clientvar"
        working_dir: /app
        ports:
            - "57389:3000"
        image: fingerprint
        environment:
            - DATABASE_URL=postgresql://postgres:P4XDN4kAeEr98gdqtW5K@db:5432/fingerprint
        depends_on:
            - db

    db:
        image: postgres:13
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: P4XDN4kAeEr98gdqtW5K
            POSTGRES_DB: fingerprint
        ports:
            - "5432:5432"
        volumes:
            - db-data:/var/lib/postgresql/data

volumes:
    db-data:
